// Sort
export const SORT_POPULAR = "POPULARSORT"
export const SORT_PRICE_HL = "POPULARHL"
export const SORT_PRICE_LH = "POPULARLH"
export const SORT_RATING = "RATINGS"
export const SORT_PRICE_DATE = "DATE"

// Redux
export const AUTHORIZE_LOGIN = "AUTHORIZELOGIN"
export const AUTHORIZE_LOGOUT = "AUTHORIZELOGOUT"
export const THEME_CHANGE = "THEMECHANGE"
export const LANGUAGE_CHANGE = "LANGUAGECHANGE"
export const UPDATE_CARTS = "UPDATECARTS"
export const REMOVE_CARTS = "REMOVECARTS"
export const CHANGE_THEME = "CHANGETHEME"

// Path
export const ROUTE_HOME = "/"
export const ROUTE_EXPLORE = "/explore"
export const ROUTE_PRODUCT_DETAIL = "/product_detail"
export const ROUTE_CART = "/cart"
export const ROUTE_CONTACT = "/contact"
export const ROUTE_SHIPPING = "/shipping_and_return"
export const ROUTE_SIGN_IN = "/signin"
export const ROUTE_SIGN_UP = "/signup"
export const ROUTE_USER_INFO = "/userinfo"
export const ROUTE_UPDATE_INFO = "/updateinfo"
export const ROUTE_FAVORITES = "/user_favorites"
export const ROUTE_DISCOUNT = "/discounts"
export const ROUTE_ORDER = "/orders"
export const ROUTE_NOTIFICATION = "/notifications"