export {default as CartPage} from './CartPage'
export {default as ContactPage} from './ContactPage'
export {default as ExplorePage} from './ExplorePage'
export {default as HomePage} from './HomePage'
export {default as ProductDetailPage} from './ProductDetailPage'
export {default as ShippingDetailPage} from './ShippingDetailPage'